export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE= "FETCH_PRODUCT_FAILURE";

export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAILURE = "FETCH_STOCK_FAILURE";

export const FETCH_LOGGEDUSER_SUCCESS = "FETCH_LOGGEDUSER_SUCCESS";
export const FETCH_LOGGEDUSER_FAILURE = "FETCH_LOGGEDUSER_FAILURE";

export const FETCH_COUNTS_SUCCESS = "FETCH_COUNTS_SUCCESS";
export const FETCH_COUNTS_FAILURE = "FETCH_COUNTS_FAILURE"

export const FETCH_PROCESSORDERS_SUCCESS =  "FETCH_PROCESSORDERS_SUCCESS";
export const FETCH_PROCESSORDERS_FAILURE = "FETCH_PROCESSORDERS_FAILURE";

export const FETCH_ENQUIRIES_SUCCESS = "FETCH_ENQUIRIES_SUCCESS";
export const FETCH_ENQUIRIES_FAILURE = "FETCH_ENQUIRIES_FAILURE";

export const FETCH_CANCLEORDERS_SUCCESS = "FETCH_CANCLEORDERS_SUCCESS";
export const FETCH_CANCLEORDERS_FAILURE = "FETCH_CANCLEORDERS_FAILURE";

export const FETCH_REURNEDORDERS_SUCCESS = "FETCH_REURNEDORDERS_SUCCESS";
export const FETCH_REURNEDORDERS_FAILURE = "FETCH_REURNEDORDERS_FAILURE";

export const FETCH_PINCODE_SUCCESS = "FETCH_PINCODE_SUCCESS";
export const FETCH_PINCODE_FAILURE = "FETCH_PINCODE_FAILURE";

export const FETCH_BULKORDERS_SUCCESS = "FETCH_BULKORDERS_SUCCESS";
export const FETCH_BULKORDERS_FAILURE = "FETCH_BULKORDERS_FAILURE";

export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILURE = "FETCH_ACCOUNT_FAILURE";

export const FETCH_COUPONS_SUCCESS = "FETCH_COUPONS_SUCCESS";
export const FETCH_COUPONS_FAILURE = "FETCH_COUPONS_FAILURE";









